[[
love.system.setClipboardText
love.system.vibrate
love.system.openURL
love.system.getPowerInfo
love.system.getOS
love.system.getProcessorCount
love.audio.rewind
love.audio.setVelocity
love.audio.setDistanceModel
love.audio.resume
love.audio.getDopplerScale
love.audio.play
love.audio.setOrientation
love.audio.stop
love.audio.newSource
love.audio.getSourceCount
love.audio.setVolume
love.audio.getVelocity
love.audio.getPosition
love.audio.getOrientation
love.audio.setPosition
love.audio.pause
love.audio.getVolume
love.audio.setDopplerScale
love.physics.newMouseJoint
love.physics.newFixture
love.physics.newWheelJoint
love.physics.newEdgeShape
love.physics.newBody
love.physics.newChainShape
love.physics.setMeter
love.physics.newWorld
love.physics.newWeldJoint
love.physics.newRopeJoint
love.physics.getMeter
love.physics.newGearJoint
love.physics.newRectangleShape
love.physics.newFrictionJoint
love.physics.newPulleyJoint
love.physics.newPrismaticJoint
love.physics.newMotorJoint
love.physics.newRevoluteJoint
love.physics.newCircleShape
love.physics.newPolygonShape
love.physics.newDistanceJoint
love.window.fromPixels
love.window.requestAttention
love.window.toPixels
love.window.isVisible
love.window.getDisplayName
love.window.getPixelScale
love.window.isOpen
love.window.setTitle
love.window.getMode
love.window.maximize
love.window.getTitle
love.window.setMode
love.window.setIcon
love.window.minimize
love.window.getFullscreenModes
love.window.setFullscreen
love.window.getFullscreen
love.window.getPosition
love.window.setDisplaySleepEnabled
love.window.isDisplaySleepEnabled
love.window.getIcon
love.window.setPosition
love.window.showMessageBox
love.window.hasMouseFocus
love.window.isMaximized
love.window.hasFocus
love.event.pump
love.event.poll
love.event.push
love.event.wait
love.event.quit
love.timer.step
love.timer.getDelta
love.timer.getTime
love.timer.getFPS
love.timer.sleep
love.thread.newThread
love.thread.newChannel
love.mouse.setX
love.mouse.getSystemCursor
love.mouse.isGrabbed
love.mouse.isDown
love.mouse.newCursor
love.mouse.setVisible
love.mouse.getRelativeMode
love.mouse.setCursor
love.mouse.getPosition
love.mouse.hasCursor
love.mouse.setY
love.mouse.setGrabbed
love.mouse.setPosition
love.mouse.getX
love.mouse.getY
love.mouse.isVisible
love.mouse.setRelativeMode
love.image.newImageData
love.image.newCompressedData
love.joystick.saveGamepadMappings
love.joystick.setGamepadMapping
love.joystick.getJoysticks
love.joystick.loadGamepadMappings
love.touch.getPressure
love.touch.getTouches
love.filesystem.unmount
love.filesystem.write
love.filesystem.getLastModified
love.filesystem.init
love.filesystem.newFileData
love.filesystem.isSymlink
love.filesystem.createDirectory
love.filesystem.lines
love.filesystem.exists
love.filesystem.newFile
love.filesystem.getSaveDirectory
love.filesystem.mount
love.filesystem.getWorkingDirectory
love.filesystem.getSize
love.filesystem.setRequirePath
love.filesystem.setSymlinksEnabled
love.filesystem.getDirectoryItems
love.filesystem.setIdentity
love.filesystem.setSource
love.filesystem.read
love.filesystem.getIdentity
love.filesystem.areSymlinksEnabled
love.filesystem.getAppdataDirectory
love.filesystem.getSource
love.filesystem.getUserDirectory
love.filesystem.getRealDirectory
love.filesystem.load
love.filesystem.remove
love.filesystem.isDirectory
love.filesystem.isFile
love.filesystem.isFused
love.filesystem.getRequirePath
love.filesystem.getSourceBaseDirectory
love.math.randomNormal
love.math.isConvex
love.math.gammaToLinear
love.math.noise
love.math.getRandomSeed
love.math.setRandomSeed
love.math.linearToGamma
love.math.triangulate
love.math.setRandomState
love.math.getRandomState
love.math.random
love.math.newRandomGenerator
love.math.decompress
love.math.newBezierCurve
love.graphics.stencil
love.graphics.line
love.graphics.newParticleSystem
love.graphics.setFont
love.graphics.isWireframe
love.graphics.getDefaultFilter
love.graphics.setDefaultFilter
love.graphics.shear
love.graphics.print
love.graphics.newShader
love.graphics.getCompressedImageFormats
love.graphics.getCanvas
love.graphics.getStencilTest
love.graphics.points
love.graphics.scale
love.graphics.getLineStyle
love.graphics.setBlendMode
love.graphics.getLineJoin
love.graphics.draw
love.graphics.getWidth
love.graphics.translate
love.graphics.intersectScissor
love.graphics.discard
love.graphics.setWireframe
love.graphics.setStencilTest
love.graphics.setShader
love.graphics.origin
love.graphics.push
love.graphics.setScissor
love.graphics.clear
love.graphics.setPointSize
love.graphics.setNewFont
love.graphics.setLineWidth
love.graphics.newSpriteBatch
love.graphics.rectangle
love.graphics.setLineStyle
love.graphics.getBlendMode
love.graphics.setColorMask
love.graphics.getScissor
love.graphics.setColor
love.graphics.setCanvas
love.graphics.printf
love.graphics.isGammaCorrect
love.graphics.newCanvas
love.graphics.rotate
love.graphics.reset
love.graphics.setBackgroundColor
love.graphics.present
love.graphics.pop
love.graphics.getRendererInfo
love.graphics.polygon
love.graphics.newMesh
love.graphics.newScreenshot
love.graphics.newQuad
love.graphics.newVideo
love.graphics.getDimensions
love.graphics.newImage
love.graphics.getColor
love.graphics.newFont
love.graphics.getSupported
love.graphics.getHeight
love.graphics.circle
love.graphics.getColorMask
love.graphics.ellipse
love.graphics.getSystemLimits
love.graphics.setLineJoin
love.graphics.getCanvasFormats
love.graphics.newImageFont
love.graphics.getLineWidth
love.graphics.newText
love.graphics.getFont
love.graphics.getBackgroundColor
love.graphics.getPointSize
love.graphics.getShader
love.graphics.getStats
love.sound.newSoundData
love.keyboard.hasTextInput
love.keyboard.getScancodeFromKey
love.keyboard.isDown
love.keyboard.setKeyRepeat
love.keyboard.setTextInput
love.keyboard.hasKeyRepeat
love.keyboard.isScancodeDown
love.video.newVideoStream

]]